name: test-ui ELF

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
          unzip -q android-ndk-r27c-linux.zip
          echo "NDK=$PWD/android-ndk-r27c" >> $GITHUB_ENV

      - name: Build test-ui
        run: |
          mkdir build && cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=${NDK}/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=arm64-v8a \
                -DANDROID_SURFACE_IMGUI_BUILD_TESTING=ON \
                -DANDROID_SURFACE_IMGUI_BUILD_STATIC=OFF \
                -DANDROID_SURFACE_IMGUI_BUILD_SHARED=OFF \
                -S .. -B . -G Ninja
          cmake --build . --target test-ui

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test-ui
          path: build/tests/arm64-v8a/test-ui
